export * from "./getCustomIndex2DividerBackgroundPath";
export * from "./getCustomIndex2DividerIconLeft";
export * from "./getCustomIndex2DividerTabIndentSize";
export * from "./getCustomIndex2DividerTabSize";
export * from "./getCustomIndex2DividerTabsCount";
export * from "./objects";
export * from "./showCustomIndex2DividerTabIcon";
export * from "./showCustomIndex2DividerTabTitle";
export * from "./toDivider";
